### PR TITLE
fix broken cdnjs link

### PR DESCRIPTION
**Pull request by hrldcpr**

### CODE REVIEW

**Comment by wout** [comment]
Thanks for letting us know. I won't merge this because the docs need to be built form source:

http://svgjs.com/contributing/documentation/

But I fixed in the meantime:

http://svgjs.com/installation/

**Comment by hrldcpr** [comment]
Cool 👍 (although I don't actually see how your commit 153f8d0 is different from this PR… but whatever, fixed is fixed!)

**Comment by wout** [comment]
I'm sorry, you're right 😳 . I read it the wrong way and though it was a pull request for `master`. Double thanks I guess. 😋

**Comment by hrldcpr** [comment]
Haha cool, I'm just glad I'm not hallucinating 🙉

**Pull request closed without merging**
