### PR TITLE
added documentation for SVG.Point - closing #14

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This is my first attempt at writing documentation in Kirby. @wout will you take a quick look and check that I did everything right?

I have tested it by running `php -S localhost:8000` locally but I could not get headline anchor links to work locally. is there some magic happening once it's build via Github Pages?

### CODE REVIEW

**Comment by dotnetCarpenter** [comment]
BTW, this PR is for #14

**Comment by wout** [comment]
Looks fine to me. The anchor links are generated in the statify.php file. Quick and dirty, but it works for now.

**Comment by dotnetCarpenter** [comment]
@wout nice. Still not sure I get it. Do I need to build something or invoke statify.php somehow before merging with master? I remember you wrote something on slack but I can't find it.

**Comment by dotnetCarpenter** [comment]
ok. I think I get it but just want to check with you. I'll build the site via `php statify.php` and then change to the master branch and replace everything with the content of `static`. Right?

**Comment by dotnetCarpenter** [comment]
Oh, wait. There is also something for building the CSS which doesn't work on linux.

`npm run build` yields:
```
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
```

But I guess I don't need that anyway. The `assets/` seems fine.

**Comment by dotnetCarpenter** [comment]
I made a mistake and use `SVG.Number` instead of `SVG.Point` in one of the examples. Just leaving a reminder here...

**Pull request merged**
