### PR TITLE
Transforms and plugins

### PR DESCRIPTION
**Pull request by saivan**
WIP: Just added a plug for the svg.declarative.js

### CODE REVIEW

**Comment by saivan** [comment]
Also, I'd like to document the boxes,
but as far as I understood; `rbox` is the only one that needs to be re-documented, as it can now produce boxes relative to another element in the dom right?

**Comment by saivan** [comment]
I'm also going to document how to build these docs on a local machine once I figure out how to do that 👍

**Comment by saivan** [comment]
Still a little more documentation to do. Should I just merge, or wait for that?

**Comment by Fuzzyma** [comment]
Do as you like. I guess as long as what you merge is correct you can do as you wish

**Comment by saivan** [comment]
Sure, did you manage to figure out how to build these scripts btw?

**Comment by saivan** [comment]
Ooooooooookay, I got it building. But its slightly annoying: I had to chmod one of the binaries because they weren't executable by default 0_0

**Comment by saivan** [comment]
So it seems that the node modules were being bundled with the repo, instead I packaged a lock file that locks everything to the right version so we don't need to do that. The reason the docs weren't working was because one of the bundled files needed a `chmod`.

Does this all look good to you?

**Comment by Fuzzyma** [comment]
Well - cannot really see in 6421 changed files :D. But I guess so^^

**Pull request merged**
